import Head from 'next/head'

export default function Home() {
  return (
    <div className='flex h-screen'>
      <div className='m-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1 className='text-2xl text-yellow-500'>bonski.dev</h1>
      <p>Segera mengudara dalam waktu dekat!</p>
      </div>
      
    </div>
  )
}
